DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INTEGER PRIMARY KEY NOT NULL,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	name TEXT NOT NULL
);

DROP TABLE IF EXISTS feeds;
CREATE TABLE feeds (
	id INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	url TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS news;
CREATE TABLE news (
	id INTEGER PRIMARY KEY NOT NULL,
	guid TEXT NOT NULL,
	title TEXT NOT NULL,
	contents TEXT NOT NULL,
	datetime INTEGER NOT NULL,
	url TEXT NOT NULL,
	feed_id INTEGER NOT NULL,
	favorite INTEGER NOT NULL DEFAULT 0,
	unread INTEGER NOT NULL DEFAULT 1,
	UNIQUE(feed_id, guid),
	FOREIGN KEY (feed_id) REFERENCES feeds (id) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS filters;
CREATE TABLE filters (
	id INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	text TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

DROP TABLE IF EXISTS feed_filters;
CREATE TABLE feed_filters (
	id INTEGER PRIMARY KEY NOT NULL,
	feed_id INTEGER NOT NULL,
	filter_id INTEGER NOT NULL,
	FOREIGN KEY (feed_id) REFERENCES feeds (id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (filter_id) REFERENCES filters (id) ON UPDATE CASCADE ON DELETE CASCADE
);
