DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INTEGER PRIMARY KEY NOT NULL,
	username TEXT NOT NULL,
	password TEXT NOT NULL,
	name TEXT NOT NULL
);

DROP TABLE IF EXISTS feeds;
CREATE TABLE feeds (
	id INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	url TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id)
);

DROP TABLE IF EXISTS news;
CREATE TABLE news (
	id INTEGER PRIMARY KEY NOT NULL,
	title TEXT NOT NULL,
	contents TEXT NOT NULL,
	datetime INTEGER NOT NULL,
	url TEXT NOT NULL,
	feed_id INTEGER NOT NULL,
	favorite INTEGER NOT NULL DEFAULT 0,
	unread INTEGER NOT NULL DEFAULT 1,
	FOREIGN KEY (feed_id) REFERENCES feeds (id)
);

DROP TABLE IF EXISTS filters;
CREATE TABLE filters (
	id INTEGER PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	text TEXT NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id)
);

DROP TABLE IF EXISTS feed_filter;
CREATE TABLE feed_filter (
	id INTEGER PRIMARY KEY NOT NULL,
	feed_id INTEGER NOT NULL,
	filter_id INTEGER NOT NULL,
	FOREIGN KEY (feed_id) REFERENCES feeds (id),
	FOREIGN KEY (filter_id) REFERENCES filters (id)
);
